In [1]:
import pandas as pd

In [2]:
from sklearn.linear_model import LogisticRegression

In [3]:
from sklearn.svm import SVC

In [4]:
from sklearn.ensemble import RandomForestClassifier 

In [5]:
from sklearn.datasets import load_digits

In [6]:
import numpy as np

In [7]:
digits=load_digits()

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target, test_size=0.3)

In [10]:
lr=LogisticRegression()

In [11]:
lr.fit(X_train,y_train)

C:\Users\himanshu\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [12]:
lr.score(X_test,y_test)

0.9611111111111111

In [13]:
svm=SVC()

In [14]:
svm.fit(X_train,y_train)

SVC()

In [15]:
svm.score(X_test,y_test)

0.987037037037037

In [16]:
ref=RandomForestClassifier(n_estimators=40)

In [17]:
ref.fit(X_test,y_test)

RandomForestClassifier(n_estimators=40)

In [18]:
ref.score(X_test,y_test)

1.0

In [19]:
from sklearn.model_selection import KFold

In [20]:
 kf=KFold(n_splits=3) #how many folds we want to create

In [21]:
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [22]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [27]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [28]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

C:\Users\himanshu\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [29]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.987037037037037

In [30]:
get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test)

0.9666666666666667

In [31]:
from sklearn.model_selection import StratifiedKFold

In [32]:
folds=StratifiedKFold(n_splits=3)

In [33]:
scores_l=[]

In [34]:
scores_rf=[]

In [35]:
scores_svm=[]

In [38]:
for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [40]:
scores_l

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [41]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [42]:
scores_rf

[0.9282136894824707, 0.9515859766277128, 0.9148580968280468]

# cross_val_score function

In [43]:
from sklearn.model_selection import cross_val_score

# Logistic regression model performance using cross_val_score

In [44]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

# SVM model performance using cross_val_score

In [46]:
cross_val_score(SVC(), digits.data, digits.target,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

# RandomForestClassifier model performance using cross_val_score

In [47]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target,cv=3)

array([0.92320534, 0.94824708, 0.92654424])

In [48]:
cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target,cv=3)

array([0.82136895, 0.87312187, 0.84474124])

In [50]:
cross_val_score(RandomForestClassifier(n_estimators=60), digits.data, digits.target,cv=3)

array([0.93489149, 0.95659432, 0.92320534])